name: Frontend Lint & Test

env:
  FRONTEND_IMAGE: us-central1-docker.pkg.dev/flight-planner-app-464807/flight-planner-frontend/frontend

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
  deploy-frontend:
    name: Build & Deploy Frontend
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Frontend Docker image
        run: |
          docker build -t $FRONTEND_IMAGE .
          docker push $FRONTEND_IMAGE

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy flight-planner-frontend \
            --image=$FRONTEND_IMAGE \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated